import random
import pyttsx3
import time

engine = pyttsx3.init()
engine.setProperty('rate', 180)
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)

assistant_name = "Max"

def speak(text):
    if assistant_name in text:
        text = text.replace(assistant_name, "I")
    engine.say(text)
    engine.runAndWait()

def get_health_tips():
    """
    Fetches and speaks a random selection of two to three health tips and medical information.
    """
    health_tips = [
    "Limit sugary drinks to reduce the risk of heart disease and type 2 diabetes.",
    "Eat nuts and seeds for protein, fiber, vitamins, and minerals.",
    "Avoid ultra-processed foods to prevent obesity and chronic conditions.",
    "Include protein with every meal to balance blood sugar.",
    "Eat oily fish for essential omega-3 fatty acids.",
    "Choose whole grains over refined grains for better nutrition.",
    "Eat a variety of colored fruits and vegetables for a wide range of antioxidants.",
    "Include healthful fats found in avocado, oily fish, and vegetable oils.",
    "Use extra virgin olive oil for its benefits to the heart, blood pressure, and weight.",
    "A balanced diet of fruits, vegetables, whole grains, and lean proteins can help prevent or manage conditions like heart disease, stroke, and diabetes.",
    "Exercise burns calories, boosts your metabolism, and releases hormones that improve your mood.",
    "Getting enough sleep helps maintain high energy levels, improves brain function, and enhances emotional well-being.",
    "Drinking water helps flush toxins from your body, regulate blood pressure and body temperature, and may help you get healthy skin.",
    "Water is crucial for the proper functioning of your body. Stay hydrated by drinking at least 8 glasses of water every day.",
    "Include fruits, vegetables, whole grains, lean proteins, and healthy fats in your diet. Avoid excessive consumption of processed foods, sugary beverages, and fast food.",
    "Practice portion control by using smaller plates and serving sizes.",
    "Limit saturated and trans fats found in fried foods, baked goods, and processed snacks.",
    "Incorporate probiotic-rich foods like yogurt, kefir, and sauerkraut to support gut health.",
    "Limit added sugars in your diet by avoiding sugary drinks, candies, and desserts.",
    "Eat breakfast every day to jumpstart your metabolism and fuel your body.",
    "Cook meals at home using fresh ingredients to control the quality and quantity of your food.",
    "Limit salt intake to reduce the risk of high blood pressure and heart disease.",
    "Stay active throughout the day by taking short walks, using stairs, or stretching regularly.",
    "Practice good hygiene by washing your hands frequently, especially before eating and after using the restroom.",
    "Practice stress management techniques like yoga, meditation, or deep breathing to reduce stress levels.",
    "Get regular check-ups and screenings to detect and prevent health problems early.",
    "Limit alcohol consumption to reduce the risk of liver disease and other health problems.",
    "Avoid smoking and exposure to secondhand smoke to protect your lungs and heart.",
    "Wear sunscreen to protect your skin from harmful UV rays.",
    "Practice safe sex to reduce the risk of sexually transmitted infections.",
    "Maintain a healthy weight by eating a balanced diet and staying active.",
    "Stay hydrated by drinking plenty of water throughout the day.",
    "Eat a variety of foods to ensure you get all the nutrients your body needs.",
    "Get regular physical activity to improve your overall health and well-being.",
    "Practice good sleep hygiene by going to bed and waking up at the same time every day.",
    "Limit screen time before bed to improve the quality of your sleep.",
    "Practice good posture to prevent back and neck pain.",
    "Take breaks from sitting by standing, stretching, or walking around.",
    "Practice good hand hygiene by washing your hands regularly.",
    "Avoid touching your face to reduce the spread of germs.",
    "Practice proper food safety by cooking foods to the correct temperature and storing them properly.",
    "Practice safe driving habits to reduce the risk of accidents and injuries.",
    "Wear protective gear when participating in sports or activities that could result in injury.",
    "Practice sun safety by wearing sunscreen, sunglasses, and protective clothing.",
    "Stay informed about health issues and make informed decisions about your health.",
    "Practice gratitude and mindfulness to improve your mental health.",
    "Surround yourself with positive people who support your health goals.",
    "Practice good oral hygiene by brushing and flossing regularly.",
    "Get regular dental check-ups to maintain good oral health.",
    "Limit caffeine intake to reduce the risk of anxiety and insomnia.",
    "Practice deep breathing exercises to reduce stress and anxiety.",
    "Practice relaxation techniques like yoga or meditation to reduce stress levels.",
    "Engage in hobbies and activities that bring you joy and relaxation.",
    "Spend time outdoors to improve your mood and mental well-being.",
    "Practice mindful eating by savoring each bite and eating slowly.",
    "Practice self-care by taking time for yourself and doing activities you enjoy.",
    "Practice gratitude by expressing thanks for the good things in your life.",
    "Practice forgiveness to let go of negative emotions and move forward.",
    "Practice kindness by helping others and showing compassion.",
    "Practice mindfulness by being present in the moment and aware of your thoughts and feelings.",
    "Practice acceptance by acknowledging and accepting things as they are.",
    "Practice resilience by bouncing back from setbacks and challenges.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Practice optimism by focusing on the positive aspects of life.",
    "Practice patience by accepting things that are out of your control.",
    "Practice empathy by understanding and sharing the feelings of others.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks daily.",
    "Practice mindfulness by meditating or practicing yoga regularly.",
    "Practice kindness by performing random acts of kindness for others.",
    "Practice forgiveness by letting go of past grievances and moving forward.",
    "Practice resilience by learning from failures and setbacks.",
    "Practice self-compassion by being understanding and gentle with yourself.",
    "Practice optimism by maintaining a positive outlook on life.",
    "Practice patience by staying calm in frustrating situations.",
    "Practice empathy by listening actively and trying to understand others' perspectives.",
    "Practice gratitude by acknowledging and appreciating the good things in your life.",
    "Practice mindfulness by focusing on the present moment and accepting it without judgment.",
    "Practice kindness by being considerate and compassionate towards others.",
    "Practice forgiveness by letting go of past hurts and moving forward.",
    "Practice resilience by adapting to change and overcoming challenges.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Practice optimism by maintaining a positive outlook on life.",
    "Practice patience by accepting things as they are and waiting calmly for results.",
    "Practice empathy by understanding and sharing the feelings of others.",
    "Practice gratitude by expressing thanks for the good things in your life.",
    "Stay positive and optimistic to improve your mental and physical health.",
    "Practice meditation or mindfulness to reduce stress and improve focus.",
    "Engage in regular physical activity to strengthen your body and mind.",
    "Maintain a healthy diet rich in fruits, vegetables, whole grains, and lean proteins.",
    "Stay hydrated by drinking plenty of water throughout the day.",
    "Get enough sleep to allow your body and mind to rest and recharge.",
    "Practice good hygiene by washing your hands regularly and keeping your living space clean.",
    "Avoid unhealthy habits like smoking, excessive drinking, and drug use.",
    "Stay connected with friends and family to maintain a strong support network.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice gratitude by acknowledging the good things in your life.",
    "Set realistic goals and work towards them to maintain a sense of purpose and accomplishment.",
    "Practice mindfulness by being present in the moment and appreciating the simple joys of life.",
    "Engage in activities that bring you joy and fulfillment, whether it's hobbies, sports, or creative pursuits.",
    "Limit exposure to negative news and media to reduce stress and anxiety.",
    "Practice deep breathing exercises or meditation to calm your mind and reduce stress.",
    "Seek support from friends, family, or a therapist if you are feeling overwhelmed or anxious.",
    "Practice self-care by taking time for yourself and doing activities that nourish your body and soul.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet rich in fruits, vegetables, whole grains, and lean proteins.",
    "Get enough sleep to allow your body to rest and recharge.",
    "Limit alcohol consumption and avoid smoking to protect your health.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks daily.",
    "Engage in activities that challenge your mind, such as puzzles, games, or learning new skills.",
    "Stay connected with others by maintaining relationships with friends and family.",
    "Practice relaxation techniques, such as yoga or meditation, to reduce stress and anxiety.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice mindfulness by being present in the moment and savoring the experiences of life.",
    "Engage in regular physical activity to boost your mood and improve your overall well-being.",
    "Eat a balanced diet that includes a variety of nutrients to support your physical and mental health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice gratitude by acknowledging the blessings in your life and expressing thanks.",
    "Stay connected with others and maintain a strong support network.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Limit exposure to negative influences, such as toxic relationships or media that promote fear and negativity.",
    "Seek professional help if you are struggling with mental health issues, such as anxiety, depression, or addiction.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet rich in fruits, vegetables, whole grains, and lean proteins to nourish your body.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by focusing on the present moment and letting go of worries about the past or future.",
    "Stay connected with others by maintaining relationships with friends and family members.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, sports, or creative pursuits.",
    "Practice gratitude by acknowledging the good things in your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-care by prioritizing your physical and emotional well-being.",
    "Set boundaries to protect your time and energy from being overextended.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Stay connected with others and maintain supportive relationships.",
    "Engage in activities that challenge your mind and stimulate your creativity.",
    "Practice mindfulness by being present in the moment and letting go of distractions.",
    "Seek help from a mental health professional if you are struggling with stress, anxiety, or depression.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and celebrate your progress towards them.",
    "Practice gratitude by keeping a gratitude journal or expressing thanks to others.",
    "Engage in regular physical activity that you enjoy to boost your mood and energy levels.",
    "Eat a balanced diet that includes a variety of nutrients to support your overall health.",
    "Get enough sleep to allow your body and mind to rest and rejuvenate.",
    "Practice mindfulness by paying attention to your thoughts and feelings without judgment.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that bring you joy and fulfillment, such as hobbies, creative pursuits, or volunteering.",
    "Practice gratitude by focusing on the positive aspects of your life and expressing thanks to others.",
    "Seek support from a mental health professional if you are struggling with your mental health.",
    "Practice self-care by prioritizing your physical, emotional, and mental well-being.",
    "Set boundaries to protect yourself from stress and overwhelm.",
    "Stay active by engaging in regular physical activity that you enjoy.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    "Get enough sleep to allow your body and mind to rest and recover.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Stay connected with others and cultivate meaningful relationships.",
    "Engage in activities that stimulate your mind and challenge you intellectually.",
    "Practice mindfulness by being present in the moment and appreciating the simple pleasures of life.",
    "Seek help from a mental health professional if you are struggling with your mental health.",
    "Practice self-compassion by treating yourself with kindness and understanding.",
    "Set realistic goals and work towards them at your own pace.",
    "Practice gratitude by keeping a gratitude journal or taking time each day to reflect on what you are thankful for.",
    "Engage in regular physical activity that you enjoy to boost your mood and improve your overall health.",
    "Eat a balanced diet that nourishes your body and supports your overall health.",
    ]
    random.shuffle(health_tips)
    for tip in health_tips[:random.randint(3, 5)]:
        speak(tip)
        time.sleep(1)